#!/bin/bash
trap ctrl_c SIGHUP
trap ctrl_c SIGINT
trap ctrl_c SIGILL
trap ctrl_c SIGILL

function ctrl_c() {
    echo "Exiting..."
    sudo rm "/dev/$file"
    exit 0
}

cd "$(dirname "$0")"
./on
channel="$1"
if [[ -z "$channel" ]]; then
    channel=22
fi
sudo sdptool add --channel=$channel SP
echo "Channel=$channel"
file="rfcomm"
i=0
while [[ -e "/dev/${file}$i" ]] ; do
    let i++
done
file="${file}$i"
sudo mknod -m 666 "/dev/$file" c 216 0
echo "SerialPort=/dev/$file"
rfcomm watch "/dev/$file" "$channel" /sbin/agetty "$file" 115200 linux
