#!/bin/bash
trap ctrl_c SIGHUP
trap ctrl_c SIGINT
trap ctrl_c SIGILL
trap ctrl_c SIGILL

function ctrl_c() {
    echo "Exiting..."
    sudo rm "$file"
    exit 0
}

cd "$(dirname "$0")"
./on
if [[ -n "$2" ]]; then
    channel="$1"
    address="$2"

else
if [[ -n "$1" ]]; then
    channel=22
    address="$1"
else
    echo "No channel and MAC address specified!"
    exit 4
fi
fi
echo "Address=$address"
sudo sdptool add --channel=$channel SP
echo "Channel=$channel"
file="/dev/rfcomm"
i=0
while [[ -e "${file}$i" ]] ; do
    let i++
done
file="${file}$i"
sudo mknod -m 666 "$file" c 216 0
echo "SerialPort=$file"
rfcomm connect "$file" "$address" "$channel"
