#!/bin/bash
sudo apt-get update
sudo apt-get dist-upgrade
echo "Updating pip packages..."
pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U --user
echo "Cleaning..."
sh $(dirname "$0")/clear
