#!/bin/bash
echo "Running examples..."
echo "============="
echo "Testing with C++..."
cd $(dirname "$0")/Cpp
mkdir build
cd build
cmake ..
make
chmod +x DisplayImage
./DisplayImage "$(realpath ../../image.png)"
cd ..
rm -r build/
echo "C++ test done."
echo "============="
echo "A Python 2 example can be run."
read -p "Continue (y/n)?" CONT
if [ "$CONT" = "y" ]; then
  echo "Testing with Python..."
  cd /usr/local/share/OpenCV/samples/python
  python camshift.py
  echo "============="
  echo "Done."
fi
