#!/bin/bash
temp="$(zenity --scale --min-value=1000 --value=1200 --max-value=25000 --step=100 --text="Select the color temperature in Kelvin:" 2> /dev/null)"
if [[ -n "$temp" ]]; then
    redshift -O "$temp"
fi
