#!/bin/bash
if [ -n "$(which gsettings)" ]; then
    if [ "$(gsettings get org.gnome.settings-daemon.plugins.color night-light-enabled)" == "true" ]; then
        gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled false

    else
    	gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
    fi
fi
