#!/bin/bash
d="$1"
if [[ -z "$d" ]]; then
    read -e -p "Please specify the INDI source folder (leave empty to use \"$(pwd)\"): " d
fi
if [[ -z "$d" ]]; then
    echo "Working in: $(pwd)"
else
    cd $d
    echo "Working in: $d"
fi

echo "============= Installing dependencies ============="
sudo apt install libnova-dev libcfitsio-dev libusb-1.0-0-dev zlib1g-dev libgsl-dev build-essential \
cmake git libjpeg-dev libcurl4-gnutls-dev libtiff-dev libfftw3-dev

echo "============= Preparing ============="
if [[ -d "build" ]]; then
    echo "Build directory found."
    read -p "Remove it (y/n)?" CONT
    if [[ "$CONT" = "y" ]]; then
        rm -r build
    fi
fi
mkdir -p build/libindi
cd build/libindi
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ../../libindi
echo "============= Building ============="
read -p "Do you want to build INDI using $(nproc) jobs (faster) instead of one? (y/n)?" MJOB
if [[ "$MJOB" = "y" ]]; then
    make -j$(nproc)
else
    make
fi

echo "============= Installing ============="
sudo make install

read -p "Do you want to install all the 3rd party drivers? (y/n)?" DRIVERS
if [[ "$DRIVERS" = "y" ]]; then
    cd ..
    echo "============= Installing dependencies ============="
    sudo apt install libftdi-dev libgps-dev libraw-dev libdc1394-22-dev libgphoto2-dev libboost-dev libboost-regex-dev librtlsdr-dev liblimesuite-dev libftdi1-dev fxload
    echo "============= Preparing ============="
    mkdir 3rdparty
    cd 3rdparty
    cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ../../3rdparty
    echo "============= Building (1/2) ============="
    if [[ "$MJOB" = "y" ]]; then
        make -j$(nproc)
        echo "============= Installing (1/2) ============="
        sudo make install
        echo "============= Building (2/2) ============="
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ../../3rdparty
        make -j$(nproc)

    else
        make
        echo "============= Installing (1/2) ============="
        sudo make install
        echo "============= Building (2/2) ============="
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ../../3rdparty
        make
    fi
    echo "============= Installing (2/2) ============="
    sudo make install
fi
echo "Done."
