#!/bin/bash
cp $(dirname "$0")/settings $HOME/.config/kstarsrc
rm -r $HOME/.indi 2> /dev/null
cp -r $(dirname "$0")/indiConfig $HOME/.indi
rm -r $HOME/.local/share/kstars 2> /dev/null
cp -r $(dirname "$0")/kstarsData $HOME/.local/share/kstars
