#!/bin/bash
sudo apt install flatpak
if [ -n "$(which gnome-software)" ]; then
    sudo apt install gnome-software-plugin-flatpak
fi
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
