#!/bin/bash
echo "This script will download Oracle Java 9."
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java9-installer
sudo apt-get install oracle-java9-set-default
echo "Done."
java -version
