#!/bin/bash
echo "Installing dependencies..."
sudo apt-get install -y build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev python-numpy python-dev libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

dir=$1
if [ -z $dir ]; then
    read -e -p "Please specify an directory to download and build OpenCV: " opt
fi
cd $dir
echo "Working in: " $dir

echo "Downloading OpenCV 2.4.13.5..."
wget --output-document "OpenCV-2.4.13.5-source.zip" "https://codeload.github.com/opencv/opencv/zip/2.4.13.5"
unzip "OpenCV-2.4.13.5-source.zip"
rm "OpenCV-2.4.13.5-source.zip"
cd "opencv-2.4.13.5"
echo "============="
echo "Download done."

echo "Running CMake..."
mkdir release
cd release
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..

echo "Building..."
make -j$(nproc)

echo "Installing..."
sudo make install
sudo apt-get install -y python-opencv

echo "Configuring..."
sudo ldconfig

echo "============="
echo "OpenCV installed. Done."

echo "Checking..."
pkg-config --modversion opencv

echo "============="
echo "Configured. Done."

echo "The installed OpenCV library should be checked with some examples."
read -p "Continue (y/n)?" CONT
if [ "$CONT" = "y" ]; then
    sh $(dirname "$0")/tests/OpenCV/test-opencv2
fi
