#!/bin/bash
option=$1
if [ -z "$option" ]; then
    echo "Which packages do you want to install?"
    echo "1. Client"
    echo "2. Server"
    echo "3. Both"
    echo
    read -p "Please select an option: " option
fi

if [ "$option" == "1" ]; then
    sudo apt-get install openssh-client
    
elif [ "$option" == "2" ]; then
    sudo apt-get install openssh-server
    
else
    sudo apt-get install openssh-client openssh-server
fi
