#!/bin/bash
if [ -n "$(pgrep spotify)" ]; then
    killall spotify
    sleep 0.5
    killall spotify
    sleep 0.5
fi
sleep 2 && dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause &
spotify
