#!/bin/bash
cd "$(dirname "$0")"
interface="$(awk '{print $1}' hotspot_config)"
if [[ "$interface" == "null" ]]; then
  interfaces=()
  while read -r line; do
    interfaces+=($line "")
  done <<< "$(../net/list-net-devices)"
  interface="$(whiptail --title "Remote network manager using BT" --backtitle "By marcocipriani01"\
  --menu "Select a newtwork interface:" 15 50 8 "${interfaces[@]}" 3>&1 1>&2 2>&3)"
fi
if [[ -n "$interface" ]]; then
  echo "Configuring network interface..."
  sudo ifconfig "$interface" up
  echo "Bluetooth init..."
  ../dev/bt/off
  sudo sed -i 's#ExecStart=/usr/lib/bluetooth/bluetoothd#ExecStart=/usr/lib/bluetooth/bluetoothd -C#g' /etc/systemd/system/dbus-org.bluez.service
  sudo sed -i 's#AutoEnable=false#AutoEnable=true#g' /etc/bluetooth/main.conf
  sudo rm /dev/rfcomm* 2> /dev/null
  sudo systemctl daemon-reload
  sudo service bluetooth restart
  ../dev/bt/off
  sleep 0.5
  ../dev/bt/on
  sudo sdptool add SP
  echo "MAC address of this computer: $(../dev/bt/get-MAC)"
  sudo python py/hotspot-controller-bluetooth.py "$USER" "$interface" "$(awk '{print $2}' hotspot_config)" "$(awk '{print $3}' hotspot_config)"
fi
