#!/bin/bash
cd "$(dirname "$0")"
./kill-indi > /dev/null
if [ ! -z "$(../dev/list-serial-ports)" ]; then
    ../dev/list-serial-ports | xargs -L1 sudo chmod a+rw
fi
echo "Available serial ports:"
../dev/list-serial-ports
echo "Starting the INDI Web Manager..."
echo "Current IP:" "$(../net/ip)"
echo "Default port: 8624"
indi-web -v
