#!/bin/bash
temp=$(zenity --scale --min-value=1000 --value=1200 --max-value=25000 --step=100 --text="Please, select the color temperature in Kelvin:" 2> /dev/null)
if [ ! -z $temp ]; then
        redshift -O $temp
fi
